spring:
  datasource:
    url: jdbc:tc:postgresql:16:///spotify_youtube_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

oauth:
  encryption:
    key: 1234567890abcdef1234567890abcdef12345678123=
